#!/bin/sh

gai() { git add -i; }

gcm() { git commit -m $@; }

gst() { git status -sb; }

glog() { git log; }

gco() { git checkout $@; }

gdca() { git diff --cached; }

gd() { git diff; }

gb() { git branch $@ | tee; }

gclear() {
    git -c gc.reflogExpire=0 -c gc.reflogExpireUnreachable=0 -c gc.rerereresolved=0 -c gc.rerereunresolved=0 -c gc.pruneExpire=now gc
    git reflog expire --expire-unreachable=now --all
    git gc --prune=now
    git gc --aggressive

}

gsignall() {
    git filter-branch --commit-filter 'git commit-tree -S "$@";' -- --all
}

ggraph() {
    git log \
	--graph \
	--abbrev-commit \
	--decorate \
	--format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' \
	--all
}

gr() { git reflog --date=iso; }

grv() { git reflog show --all --pretty=short --date=iso; }

gwho() { git shortlog -n -s --no-merges; }

grmm() {
    echo "Here's the branch list that is going to be deleted:"
    git branch --merged |
	grep -v '*'

    read -r -p "Do you wanna continue with the deletion operation?[y/n]" response

    case "$response" in
	[yY][eE][sS]|[yY])
	    git branch --merged |
		grep -v '*' |
		xargs -n 1 git branch -d
	    ;;
	*)
	    echo "Cancelling..."
	    ;;
    esac
}

git-localize() {
	git config --local user.name "Taylan Dogan" && \
	git config --local user.email "git@taylandogan.info" && \
	git config --local user.signingkey ""
}